# Generated by Django 5.2.7 on 2025-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the product price', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of items available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
