# Generated by Django 4.2.25 on 2025-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='upi_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
